pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'Pipeline-job', url: 'https://github.com/VMVGITHUB/Docker-image.git'
            }
        }

    stage('Build Docker Image') {
            steps {
                script {
                    sh 'cd Pipeline-job && docker build -t hello-world-docker .'
                    }
            }
        }


        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker run -d -p 5000:5000 hello-world-docker"
                }
            }
        }
    }
}
